### ISSUE TITLE
Add package to Composer

### ISSUE THREAD

**Issue by cliffordp** [maddisondesigns/customizer-custom-controls#10]
This looks so cool.

Please submit to Composer: https://packagist.org/packages/submit

Thank you for this.

**Comment by maddisondesigns** [comment]
I'm not currently using composer so I don't have any interest in setting it up and submitting it at this time. Thanks.

**Comment by cliffordp** [comment]
If I submit a PR for the .json file, would you submit it? If not I could fork but that'd be pointless because then it wouldn't be kept updated with your repo.

**Comment by maddisondesigns** [comment]
Was just looking back over some old issues and realised I never replied here. I know it's late, but apologies for that. If you want to submit a PR for the .json file then sure, I can submit that for you. Thanks for the offer.
