### ISSUE TITLE
Dropdown Select2 Control (single select) placeholder not displayng 

### ISSUE THREAD

**Issue by Amiteb** [maddisondesigns/customizer-custom-controls#18]
if ( !$this->multiselect ) {
// When using Select2 for single selection, the Placeholder needs an empty <option> at the top of the list for it to work (multi-selects dont need this)
 echo '<option>'.$this->placeholder.'</option>';
Here Need to Add $this->placeholder between option tag please reply soon

**Comment by maddisondesigns** [comment]
The Select2 Control seems to be working fine as it is, for single selection.

Here's a vid I just created: https://share.getcloudapp.com/Z4uw6Djo

This is using my sample theme which is using the current/latest version of the code.

You can find my sample theme here if you want to try it out - https://github.com/maddisondesigns/Customizer-Custom-Controls-Sample-Theme
