### ISSUE TITLE
Can you make more controls?

### ISSUE THREAD

**Issue by UrchenkoV** [maddisondesigns/customizer-custom-controls#20]
Hello. 
Thank you for your work. Can you make these controls?
Divider
![image](https://i.postimg.cc/1t5Yp6XH/Screen-Shot.png)

2
![image](https://i.postimg.cc/YSxsG8r0/Screen-Shot-2.png)

3
![image](https://i.postimg.cc/qRbDQRCd/Screen-Shot-3.png)

4
![image](https://i.postimg.cc/mkPXnsQ1/Screen-Shot-4.png)

These screenshots are made in the Astra theme

**Comment by maddisondesigns** [comment]
Hi @UrchenkoV,

Thanks for the suggestions. I can't promise anything, but I'll definitely keep them in mind when I make some new controls.

**Comment by UrchenkoV** [comment]
@maddisondesigns 

Thanks.

**Comment by maddisondesigns** [comment]
I'm going to close this for now since it's not an issue, but I'll definitely keep these in mind when I look at creating some new controls.
