### ISSUE TITLE
[NEW FUNCTION] Responsive controls

### ISSUE THREAD

**Issue by stefanofattori** [maddisondesigns/customizer-custom-controls#29]
Hi, Please, could you add responsive data to any control? Desktop, Tablet and Smartphone.
Thank for all these controls, your project is very cool!

Thank you

**Comment by maddisondesigns** [comment]
Hi @stefacchio, It's something that I've been wanting to do but just depends if I can get the time to do it. I can't promise anything but will definitely keep this in mind for future enhancements.
Thanks.

**Comment by stefanofattori** [comment]
> Hi @stefacchio, It's something that I've been wanting to do but just depends if I can get the time to do it. I can't promise anything but will definitely keep this in mind for future enhancements. Thanks.

Hi @maddisondesigns thank you so much! I wanted to try to do it but I don’t know how to do this, I think I need to use javascript too..

**Comment by maddisondesigns** [comment]
I'm going to close this for now since there's nothing I can action just now, but will definitely be keeping it in mind for future enhancements. Thanks for raising it.
