### ISSUE TITLE
TinyMCE not working

### ISSUE THREAD

**Issue by toton333** [maddisondesigns/customizer-custom-controls#3]
I copied the files as they are, but only textarea are showing and not the toolbars. Any help?

**Comment by maddisondesigns** [comment]
For the TinyMCE Control you need to make sure that you're using WordPress 4.8 and above as the JavaScript functionality required for its use was only added in WP 4.8.

If you are using WP 4.8, I would suggest downloading my [Ephemeris theme](https://wordpress.org/themes/ephemeris/) from .org. You can see a working copy of my TinyMCE control in that theme.

I've also just created a new test site on my dev sever using the latest version of this code and the TinyMCE Control appears to be working fine.

**Comment by toton333** [comment]
I'm running 4.9.6. I downloaded your theme and compared with mine. I just used procedural approach to  register panel, section, setting, control instead of objective oriented(basically just keeping _s theme structure). It seems like to_json() is not working in the Skyrocket_TinyMCE_Custom_control class for me. I'm definitely making some silly mistake somewhere. Can you take a look at [my theme](https://github.com/toton333/airspace)

**Comment by maddisondesigns** [comment]
I've just had a very quick look. There's a couple of issues that I found. Don't know if it'll fix your TinyMCE issue, but its something to look into.

There's a js error. You're specifying a callback function that doesn't exist.
![screenshot_696](https://user-images.githubusercontent.com/2078245/41633670-49d8e516-7483-11e8-9bf1-834eff919b45.png)

This shouldn't have anything to do with it, but there's a couple of files that 404'd
![screenshot_697](https://user-images.githubusercontent.com/2078245/41633677-54cc8018-7483-11e8-9084-207f5449416d.png)

It's always a good idea to make sure you use the browser developer tools to ensure all your scripts/files are loading and there's no errors in the console.

If you still have issues, I would suggest temporarily commenting out all your other Customizer stuff and just try and add a TinyMCE control and see if that works. If it does, then you know that some of your other customizer code is causing the issue and you can re-add it back in a section at a time until you find the issue.

**Comment by toton333** [comment]
Thank you.
