### ISSUE TITLE
Slider step size cannot be smaller than 1

### ISSUE THREAD

**Issue by kyleyiyang** [maddisondesigns/customizer-custom-controls#9]
Thanks for the beautiful controls!

I tried slider, but found that it did not work when I set a step size < 1, say 0.5. I set a max=4, min=0, and step=0.5. The circle slider did not respond, which was stuck on the left end of the bar, and I could not slide it to other positions to set different values. I also downloaded your ephemal theme, and went to your layout/container width control, which has a slider with step=5 and works perfectly. I tried to change it to 0.5, and the slider stuck. Could you help resolve this problem? 

Thanks again.

**Comment by maddisondesigns** [comment]
Thanks for the kind words.

Yep, looks like there was an issue with specifying a step less than 1. Sorry about that.

I've just fixed this issue and pushed the new code.

The main files you'll need to update are:
js/customizer.js
inc/custom-controls.php

I've also added a new example slider to my code:
functions.php
inc/customizer.php

When adding your setting (`$wp_customize->add_setting`) use the new function I created (`skyrocket_range_sanitization`) for the `sanitize_callback`.
